### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by althe3rd** [jqwidgets/create-jqwidgets-react-app#1]
I have been using node and npm for a few years now with no issues installing and running packages like "create-react-app".

I made sure that node and npm are up to date and I installed create-jqwidgets-react-app with no errors reported.  But when I go to run create-jqwidgets-react-app my-app  I get an error "No such file or directory".

Any thoughts as to what is going on?

**Comment by jqwidgets** [comment]
Please, check the instructions here: https://www.jqwidgets.com/reactjs-components-documentation/documentation/create-react-app/index.htm
